config/routes.rb
Rails.application.routes.draw do
  root to: 'employees#index'

  resources :employees
  resources :departments, except: :destroy do
    get :new_name
    post :update_name
    get :new_parent
    post :update_parent
  end
  resources :reports, only: :index do
    get :employees, on: :collection
  end
  resources :employments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_ancestry

  validates :formed_at, presence: true

  has_many :employees, through: :employments
  has_many :versions, class_name: 'DepartmentVersion'

  alias department_id id

  def actual_version(date = Date.today)
    actual_versions(date).last || self
  end

  def actual_name(date = Date.today)
    actual_versions(date).where.not(name: nil).last&.name || name
  end

  def actual_parent(date = Date.today)
    actual_versions(date).where.not(ancestry: nil).last&.parent || parent
  end

  def self.actual_roots(date = Date.today)
    roots.map { |root| root.actual_version(date) }.select(&:root?)
  end

  def self.treeview(nodes, date)
    nodes.map do |node|
      employees_count = Employment.actual_employees_for_department(node.department_id, date).count
      new_nodes = DepartmentVersion.actual_at(date)
                                    .where(ancestry: node.department_id.to_s)
                                    .select { |v| v.last_version?(date) }

      {
        text: node.actual_name,
        nodes: treeview(new_nodes, date),
        tags: ["#{employees_count} сотрудников"],
        data: {
          department_id: node.department_id
        }
      }.reject { |_k, v| v.blank? }
    end
  end

  private

  def actual_versions(date)
    versions.actual_at(date).ordered
  end
end

app/models/department_version.rb
class DepartmentVersion < ApplicationRecord

  belongs_to :department

  validates :active_since, uniqueness: { scope: :department }
  validate :parent_dates

  scope :actual_at, -> (date) { where('active_since <= ?', date.beginning_of_day) }
  scope :ordered, -> { order(:active_since) }

  delegate :actual_name, to: :department

  def parent_dates
    if ancestry.present? && (parent.formed_at > active_since || parent.disbanded_at.present? && !(parent.formed_at..parent.disbanded_at).include?(active_since))
      errors.add(:active_since, 'должна лежать в пределах периода существования родительского отдела')
    end
  end

  def root?
    ancestry.nil?
  end

  def parent
    Department.find(ancestry)
  end

  def last_version?(date)
    department.versions.actual_at(date).where.not(ancestry: nil).max_by(&:active_since) == self
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :first_name, presence: true
  validates :middle_name, presence: true
  validates :last_name, presence: true

  has_many :departments, through: :employments

  def name
    [first_name, last_name].join(' ')
  end
end

app/models/employment.rb
class Employment < ApplicationRecord
  belongs_to :employee
  belongs_to :department

  validates :start_date, presence: true
  validate :end_date_gteq_start_date
  validate :dates_within_department_dates
  validate :one_department_per_employee

  scope :actual_employees_for_department, -> (department_id, date) { where(department_id: department_id).where('start_date <= ?', date).where('end_date >= ?', date) }

  def end_date_gteq_start_date
    if end_date.present? && start_date > end_date
      errors.add(:end_date, 'Неправильный интервал дат')
    end
  end

  def dates_within_department_dates
    if start_date < department.formed_at || (department.disbanded_at.present? && end_date > department.disbanded_at)
      errors.add(:start_date, 'Даты работы должны совпадать с датами существования отдела')
    end
  end

  def one_department_per_employee
    if self.class.where(employee: employee).where('start_date <= ?', end_date).where('end_date >= ? ', start_date).exists?
      errors.add(:start_date, 'Сотрудник уже работает в заданный период')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  helper_method :departments_collection

  def index; end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(params[:department].permit(:name, :formed_at, :disbanded_at))

    if @department.save
      flash[:success] = 'Отдел сохранен'
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])

    if @department.update(params[:department].permit(:formed_at, :disbanded_at))
      flash[:success] = 'Отдел обновлен'
      redirect_to departments_path
    else
      render :edit
    end
  end

  def new_name
    @department = Department.find(params[:department_id])
  end

  def update_name
    @department = Department.find(params[:department_id])

    @version = @department.versions.find_or_initialize_by(active_since: params[:version][:active_since])
    @version.name = params[:version][:name]

    if @version.save
      redirect_to departments_path
    else
      render :new_name
    end
  end

  def new_parent
    @department = Department.find(params[:department_id])
  end

  def update_parent
    @department = Department.find(params[:department_id])

    @version = @department.versions.find_or_initialize_by(active_since: params[:version][:active_since])
    @version.ancestry = params[:version][:department_id]

    if @version.save
      redirect_to departments_path
    else
      render :new_parent
    end
  end

  private

  def departments_params
    params.fetch(:department, {}).permit!
  end

  def departments_collection
    @departments_collection ||= Department.includes(:versions)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  helper_method :employees_collection, :resource_employee

  def index; end

  def new; end

  def create
    if resource_employee.save
      flash[:success] = 'Сотрудник создан'
      redirect_to employees_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if resource_employee.update(employee_params)
      flash[:success] = 'Сотрудник обновлен'
      redirect_to employees_path
    else
      render :edit
    end
  end

  def destroy
    resource_employee.destroy
    flash[:success] = 'Сотрудник удален'
    redirect_to employees_path
  end

  private

  def employees_collection
    @employees_collection ||= Employee.order(id: :desc)
  end

  def resource_employee
    @resource_employee ||= params[:id].present? ? Employee.find(params[:id]) : Employee.new(employee_params)
  end

  def employee_params
    params.fetch(:employee, {}).permit(:first_name, :middle_name, :last_name)
  end
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  helper_method :employments_collection

  def index; end

  def new
    @employment = Employment.new
  end

  def create
    @employment = Employment.new(params[:employment].permit(:employee_id, :department_id, :start_date, :end_date))

    if @employment.save
      redirect_to employments_path
    else
      render :new
    end
  end

  private

  def employments_collection
    @employments_collection ||= Employment.all
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    if params[:filter].present?
      @departments = Department.all
      date = params[:filter][:date].to_date
      @treeview = Department.treeview(Department.actual_roots(date), date)
    end
  end

  def employees
    @department = Department.find(params[:department_id])
    @employments = Employment.actual_employees_for_department(params[:department_id], params[:date])

    render partial: 'reports/shared/employees_table'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def toastr_flash
    flash_messages = []
    flash.each do |type, message|
      type = :success if type == 'notice'
      type = :error   if type == 'alert'
      text = "<script>
        toastr.#{type}(\"#{message}\");
      </script>"
      flash_messages << text.html_safe if message
    end

    flash_messages.join("\n").html_safe
  end
end

app/views/departments/edit.html.slim
.row
  .col-md-6
    .page-header
      h1 Редактирование отдела

    = simple_form_for @department, as: :department, url: department_path(@department), html: {class: 'login__form'} do |f|
      = f.input :formed_at, as: :string, input_html: { class: 'datepicker' }
      = f.input :disbanded_at, as: :string, input_html: { class: 'datepicker' }

      => f.button :submit, 'Сохранить', class: 'btn btn-primary'
      = link_to 'Отмена', departments_path, class: 'btn btn-default'

javascript:
  $('.datepicker').datepicker({format: 'yyyy-mm-dd'});

app/views/departments/index.html.slim
.page-header
  .pull-right
    = link_to fa_icon('plus'), new_department_path, class: 'btn btn-success'
  h1 Отделы

- if departments_collection.any?
  table.table.table-middled
    thead
      tr
        th Название
        th Родительский отдел
        th Дата формирования
        th Дата расформирования
        th.text-right
    tbody
      - departments_collection.each do |department|
        tr
          td = department.actual_name
          td = department.actual_parent&.actual_name
          td = department.formed_at
          td = department.disbanded_at
          td.text-right
            => link_to 'Перенос отдела', department_new_parent_path(department), class: 'btn btn-sm btn-primary'
            => link_to 'Изменить название', department_new_name_path(department), class: 'btn btn-sm btn-primary'
            => link_to fa_icon('pencil'), edit_department_path(department), class: 'btn btn-sm btn-primary'

- else
  center
    h3.text-muted Отделов не найдено

app/views/departments/new.html.slim
.row
  .col-md-6
    .page-header
      h1 Добавление отдела

    = simple_form_for @department, as: :department, url: departments_path, html: {class: 'login__form'} do |f|
      = f.input :name
      = f.input :formed_at, as: :string, input_html: { class: 'datepicker' }
      = f.input :disbanded_at, as: :string, input_html: { class: 'datepicker' }

      => f.button :submit, 'Сохранить', class: 'btn btn-primary'
      = link_to 'Отмена', departments_path, class: 'btn btn-default'

javascript:
  $('.datepicker').datepicker({format: 'yyyy-mm-dd'});

app/views/departments/new_name.html.slim
.row
  .col-md-12
    .page-header
      h1
        = "Изменение названия #{@department.actual_version.name}"
.row
  .col-md-6
    = simple_form_for :version, as: :version, url: department_update_name_path(@department), html: {class: 'login__form'} do |f|
      = f.input :name, label: 'Новое название'
      = f.input :active_since, as: :string, input_html: { class: 'datepicker' }, label: 'Дата, с которой оно изменено'

      => f.button :submit, 'Сохранить', class: 'btn btn-primary'
      = link_to 'Отмена', departments_path, class: 'btn btn-default'

app/views/departments/new_parent.html.slim
.row
  .col-md-12
    .page-header
      h1
        = "Перенос отдела #{@department.actual_version.name}"
.row
  .col-md-6
    - if @version.present? && @version.errors.any?
      .alert.alert-danger
        = @version.errors.full_messages
    = simple_form_for :version, as: :version, url: department_update_parent_path(@department) do |f|
      = f.input :department_id, collection: departments_collection.reject{ |d| d == @department }.map { |d| [d.actual_version.name, d.id] }, label: 'Новый родительский отдел', include_blank: false
      = f.input :active_since, as: :string, input_html: { class: 'datepicker' }, label: 'Дата, с которой осуществляется перенос'

      => f.button :submit, 'Сохранить', class: 'btn btn-primary'
      = link_to 'Отмена', departments_path, class: 'btn btn-default'

app/views/employees/edit.html.slim
.row
  .col-md-6
    .page-header
      h1 Редактирование сотрудника

    = render partial: 'employees/shared/form', locals: { employee: resource_employee, url: employee_path(resource_employee) }

app/views/employees/index.html.slim
.page-header
  .pull-right
    = link_to fa_icon('plus'), new_employee_path, class: 'btn btn-success'
  h1 Сотрудники

- if employees_collection.any?
  table.table.table-middled
    thead
      tr
        th Имя
        th Отчество
        th Фамилия
        th.text-right
    tbody
      - employees_collection.each do |employee|
        tr
          td = employee.first_name
          td = employee.middle_name
          td = employee.last_name
          td.text-right
            => link_to fa_icon('pencil'), edit_employee_path(employee), class: 'btn btn-sm btn-primary'
            => link_to fa_icon('trash'), employee_path(employee), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Вы уверены?' }

- else
  center
    h3.text-muted Сотрудников не найдено

app/views/employees/new.html.slim
.row
  .col-md-6
    .page-header
      h1 Добавление сотрудника

    = render partial: 'employees/shared/form', locals: { employee: resource_employee, url: employees_path }

app/views/employees/shared/_form.html.slim
= simple_form_for employee, as: :employee, url: url, html: { class: 'login__form' } do |f|
  = f.input :first_name
  = f.input :middle_name
  = f.input :last_name

  => f.button :submit, 'Сохранить', class: 'btn btn-primary'
  = link_to 'Отмена', employees_path, class: 'btn btn-default'

app/views/employments/index.html.slim
.page-header
  .pull-right
    = link_to fa_icon('plus'), new_employment_path, class: 'btn btn-success'
  h1 Сотрудники в отделах

- if employments_collection.any?
  table.table.table-middled
    thead
      tr
        th Сотрудник
        th Отдел
        th Начало работы
        th Конец работы
        th.text-right
    tbody
      - employments_collection.each do |employment|
        tr
          td = employment.employee.name
          td = employment.department.name
          td = employment.start_date
          td = employment.end_date
          td.text-right
            / => link_to 'Перенос отдела', department_new_parent_path(employment), class: 'btn btn-sm btn-primary'
            / => link_to 'Изменить название', department_new_name_path(employment), class: 'btn btn-sm btn-primary'
            / => link_to fa_icon('pencil'), edit_department_path(employment), class: 'btn btn-sm btn-primary'

- else
  center
    h3.text-muted Сотрудников в отделах не найдено

app/views/employments/new.html.slim
.row
  .col-md-6
    .page-header
      h1 Трудоустройство сотрудника

    = render partial: 'employments/shared/form', locals: { employment: @employment, url: employments_path }

app/views/employments/shared/_form.html.slim
= simple_form_for employment, as: :employment, url: url, html: { class: 'login__form' } do |f|
  = f.input :employee_id, collection: Employee.all.map { |e| [e.name, e.id] }, include_blank: false
  = f.input :department_id, collection: Department.all.map { |d| [d.name, d.id] }, include_blank: false
  = f.input :start_date, as: :string, input_html: { class: 'datepicker' }
  = f.input :end_date, as: :string, input_html: { class: 'datepicker' }

  => f.button :submit, 'Сохранить', class: 'btn btn-primary'
  = link_to 'Отмена', employments_path, class: 'btn btn-default'

app/views/layouts/application.html.slim
doctype html

html
  head
    title Departments

    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: :all
    = csrf_meta_tags
    = javascript_include_tag 'application'

  body
    .navbar.navbar-default.navbar-static-top
      .container
        .navbar-header
          = link_to 'Сотрудники', employees_path, class: "navbar-brand"
          = link_to 'Отделы', departments_path, class: "navbar-brand"
          = link_to 'Сотрудники в отделах', employments_path, class: "navbar-brand"
          = link_to 'Отчеты', reports_path, class: "navbar-brand"

    .container
      = yield

    = content_for :assets
    = toastr_flash

javascript:
  $('.datepicker').datepicker({format: 'yyyy-mm-dd'});

app/views/reports/index.html.slim
link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet"

.page-header
  .pull-right
  h1 Отчеты

.panel
  .panel-body
    = simple_form_for :filter, as: :filter, url: reports_path, method: :get do |f|
      .row
        .col-md-6
          = f.input :date, as: :string, input_html: { class: 'datepicker', value: params.dig(:filter, :date) || Date.today.strftime('%Y-%m-%d') }, label: false, placeholder: 'Укажите дату, на которую запрашивается информация'
        .col-md-6
          => f.button :submit, 'Применить фильтр', class: 'btn btn-primary'
          = link_to 'Сбросить фильтр', reports_path, class: 'btn btn-default'

- if @departments.present?
  .row
    .col-md-6
      .panel
        .panel-heading
          h5
            | Список отделов
      div#tree data-nodes=@treeview.to_json
    .col-md-6
      div#employeesTable

javascript:
  $employeesTable = $('#employeesTable');

  url_string = window.location.href;
  url = new URL(url_string);
  date = url.searchParams.get("filter[date]");

  $tree = $('#tree');
  $tree.treeview({
    data: $tree.data('nodes'),
    levels: 1,
    showTags: true,
    onNodeSelected: function (event, node) {
      $.ajax({
        url: '/reports/employees',
        data: {
          department_id: node.data.department_id,
          date: date,
        },
        success: function (data) {
          $employeesTable.html(data);
        }
      })
    }
  });

app/views/reports/shared/_employees_table.html.slim
.panel
  .panel-heading
    h5
      = @department.actual_name

- if @employments.exists?
  table.table.table-middled
    thead
      tr
        th ФИО сотрудника
        th Дата привязки сотрудника к отделу
    tbody
      - @employments.each do |employment|
        tr
          td = employment.employee.name
          td = employment.start_date
- else
  .alert.alert-info
    | Сотрудников не найдено